### PR TITLE
Fix array fields behaviour #2865

### LINKED ISSUE #2865: The ui with TextArray type doesn't work well.
### Expected behavior
Open and edit the records in admin panel.
### Actual behavior
There is an error `TypeError: Cannot read property 'map' of undefined` in `fields/mixins/ArrayField.js ` in 
```
renderField: function () {
		return (
			<div>
				{this.state.values.map(this.renderItem)}
				<Button ref="button" onClick={this.addItem}>Add item</Button>
			</div>
		);
	},
```
`this.state.values` is undefined
### Steps to reproduce the behavior
Enter to admin panel -> first open record for model without `TextArray` type -> then open record of model with `TextArray` type.
If I enter in the record of model with `TextArray` type, `this.state.values` in an empty array, but after enter in record without `TextArray` type it's becoming `undefined`.

And another:
I create item in `TextArray` field. If I paste numbers all works well, but if I paste text, it clears after saving.

This is the latest version from `master`

### PR DESCRIPTION
**Pull request by jstockwin**
## Description of changes
cc @suryagh 
Updated the `getInitialState` function in `ArrayField.js`

## Related issues (if any)

Should fix #2865 

## Testing

- [X] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by geloescht** [comment]
LGTM!

File: fields/mixins/ArrayField.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ function reduceValues (values) {
 module.exports = {
 	getInitialState: function () {
 		return {
-			values: Array.isArray(this.props.value) ? this.props.value.map(newItem) : this.props.value,
+			values: Array.isArray(this.props.value) ? this.props.value.map(newItem) : [],
```
Comment (jbpin) [inline fields/mixins/ArrayField.js]: ```values: Array.isArray(this.props.value) ? this.props.value.map(newItem) : [].concat(this.props.value)``` ??

**Comment by JedWatson** [comment]
Not sure why this got left for so long - thanks @jstockwin! Merging now.
