### PR TITLE
Fixed state updates on Tooltip when unmounted (fixes #2419)

### LINKED ISSUE #2419: Admin UI: state update on unmounted component
Been seeing this every so often recently. Haven't tracked down the exact cause yet.
image

### PR DESCRIPTION
**Pull request by Vultraz**
Converted `Tooltip` to a functional component and the problem went away. Also removed the `immediatelyHide` and `immediatelyShow` states in the process since they weren't being used (they weren't the cause of the problem, though).

### CODE REVIEW

File: packages/arch/packages/tooltip/src/index.js [hunk 1]
```diff
@@ -57,118 +56,122 @@ const showTooltip = (fn, defaultDelay) => {
...
-    }
-    if (this.props.hideOnMouseDown && this.ref.current) {
-      this.ref.current.addEventListener('mousedown', this.cancel, LISTENER_OPTIONS);
-    }
-    if (this.props.hideOnKeyDown) {
-      document.addEventListener('keydown', this.cancel, LISTENER_OPTIONS);
-    }
+    let cancelPendingSetState = () => {};
+
+    const cancel = () => {
```
Comment (irwin-r) [inline packages/arch/packages/tooltip/src/index.js:98]: It may be a bit more succinct/readable to pull these event handlers outside of the `useEffect` and limit the body of the `useEffect` to registering + removing the event listeners.

File: packages/arch/packages/tooltip/src/index.js [hunk 2]
```diff
@@ -57,118 +56,122 @@ const showTooltip = (fn, defaultDelay) => {
...
-    if (!this.state.isVisible) {
-      return;
-    }
-    if (this.props.hideOnMouseDown && this.ref.current) {
-      this.ref.current.removeEventListener('mousedown', this.cancel, LISTENER_OPTIONS);
-    }
-    if (this.props.hideOnKeyDown) {
-      document.removeEventListener('keydown', this.cancel, LISTENER_OPTIONS);
-    }
+Tooltip.defaultProps = {
```
Comment (irwin-r) [inline packages/arch/packages/tooltip/src/index.js:172]: The React team is deprecating `defaultProps`:

https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md

It may be worthwhile pulling these in as default argument values.

Comment (MadeByMike) [reply packages/arch/packages/tooltip/src/index.js:172]: We've got this in a bunch of places... I agree but I think we could defer this to another PR for now.

File: packages/arch/packages/tooltip/src/index.js (hunk 1 above)
Comment (Vultraz) [reply packages/arch/packages/tooltip/src/index.js:98]: I could move `cancelPendingSetState` out, but everything else uses props/state.

File: packages/arch/packages/tooltip/src/index.js (hunk 2 above)
Comment (Vultraz) [reply packages/arch/packages/tooltip/src/index.js:172]: Yes, I'll handle that separately at some point.

File: packages/arch/packages/tooltip/src/index.js (hunk 1 above)
Comment (irwin-r) [reply packages/arch/packages/tooltip/src/index.js:98]: Sorry, to clarify, I didn't mean outside of the component, but outside of the `useEffect` method.

I think `cancel`, `handleMouseEnter` and `handleMouseLeave` should all live above the `useEffect` method.

Comment (Vultraz) [reply packages/arch/packages/tooltip/src/index.js:98]: I think that makes things just a little messier since then `cancelPendingSetState` has to be managed with `useRef` as well. 🤔
