### PR TITLE
5604/fix query caching

### LINKED ISSUE #5604: local-storage query caching in admin-ui not working as intended
# Bug report

## Describe the bug

Currently the useQueryParamsFromLocalStorage method doesn't update cached values correctly.

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

- Start up a keystone-next example 
- populate a list page with a few entries 
- Change the pageSize query once (this will work fine)
- Change the pageSize query again, this will be automatically replaced by the effect.

## Expected behaviour: 

only retrieve cached queries when no queries are specified
don't cache page or pageSize params

## Actual behaviour: 

Initial query will be saved, all subsequent query changes in the url will be replaced. 
caches page and pageSize params

### PR DESCRIPTION
**Pull request by gwyneplaine**
Fixes #5604: 
* pageSize query no longer cached
* page query no longer cached 
* sortBy query now cached 
* field filters remain cached 
* column queries remain cached 
* caching effect now checks for whether the router is ready or not. 
* Added a 'reset to defaults' button**

This needs better design and thought, but gets the job done for now. 

https://user-images.githubusercontent.com/12119389/117245314-ff29b300-ae7d-11eb-8051-e82cc351dbbb.mov

### CODE REVIEW

File: packages-next/admin-ui/src/pages/ListPage/index.tsx [hunk 1]
```diff
@@ -77,11 +77,23 @@ let listMetaGraphqlQuery: TypedDocumentNode<
 function useQueryParamsFromLocalStorage(listKey: string) {
   const router = useRouter();
   const localStorageKey = `keystone.list.${listKey}.list.page.info`;
+  const cacheableQueries = ['sortBy', 'fields'];
```
Comment (mitchellhamilton) [inline packages-next/admin-ui/src/pages/ListPage/index.tsx:80]: Can we not call this "cacheable"? When I think of a cache, I think storing things so we don't have to compute them again, not storing user stuff to help them

File: packages-next/admin-ui/src/pages/ListPage/index.tsx [hunk 2]
```diff
@@ -77,11 +77,23 @@ let listMetaGraphqlQuery: TypedDocumentNode<
...
   useEffect(() => {
-    let hasSomeQueryParamsWhichAreAboutListPage = Object.keys(router.query).some(
-      x => x.startsWith('!') || x === 'page' || x === 'pageSize' || x === 'fields'
-    );
-    if (!hasSomeQueryParamsWhichAreAboutListPage) {
+    let hasSomeQueryParamsWhichAreAboutListPage = Object.keys(router.query).some(x => {
+      return x.startsWith('!') || cacheableQueries.includes(x);
+    });
+
+    if (!hasSomeQueryParamsWhichAreAboutListPage && router.isReady) {
```
Comment (mitchellhamilton) [inline packages-next/admin-ui/src/pages/ListPage/index.tsx:96]: What does router.isReady do here?

Comment (gwyneplaine) [reply packages-next/admin-ui/src/pages/ListPage/index.tsx:96]: as per the docs https://nextjs.org/docs/api-reference/next/router#router-object
it lets us know when the router fields are updated client side. 

The bug we were experience was due to the fact that the !hasSomeQueryParams... check was being run on an empty query object, despite them being present on the path when we run the effect. Most likely due to the fact that the check was happening before the router object had been updated

**Review by emmatown — APPROVED** [review]
