### PR TITLE
CalendarDay fixes

### LINKED ISSUE #1964: CalendarDay `date: null` when `isRequired: true`
# Bug report

## Describe the bug

When `CalendarDay` is required, creating fails because the GraphQL request sends the field value as `null` regardless of what the user input.

## To Reproduce

1. Define a list with `CalendarDay` `isRequired: true`

```
date: {
    type: CalendarDay,
    format: 'Do MMMM YYYY',
    yearRangeTo: new Date().getFullYear() + 30,
    isRequired: true,
},
```
2. Create a new item in that list and set the date field value

image

3. Click create

image

4. Observe outgoing GraphQL request payload

```js
{"operationName":"create","variables":{"data":{"date":null, ...}}}
```

## Expected behaviour

It should send the date value.

## System information

- OS: MacOS
- Browser: Chrome
- Keystone Versions
- Keystone Database: Postgres

```
    "@keystonejs/fields": "^5.2.0",
    "@keystonejs/keystone": "^5.0.0",
```

### PR DESCRIPTION
**Pull request by Vultraz**
Fixes #1964 independent of #1965 and does a few other things. Should be easier to do the date-fns upgrade with everything working properly.

Changes:
- Ensured format, yearRangeFrom, and yearRangeTo defaults are set correctly
- Removed non-functional yearPickerType
- Made displayed date format consistent between list and detailed views
- Moved date range validation to validateInput
- Added some vertical margins to <Alert>

### CODE REVIEW

File: packages/fields/src/types/CalendarDay/views/Field.js [hunk 1]
```diff
@@ -1,41 +1,35 @@
...
 
-  render() {
-    const { autoFocus, field, value, errors } = this.props;
-    const htmlID = `ks-input-${field.path}`;
+  return (
+    <FieldContainer>
+      <FieldLabel htmlFor={htmlID} field={field} errors={errors} />
+      <FieldInput>
+        <TextDayPicker
+          id={`ks-daypicker-${field.path}`}
```
Comment (MadeByMike) [inline packages/fields/src/types/CalendarDay/views/Field.js]:
```suggestion
          id={htmlID}
```

Comment (Vultraz) [reply packages/fields/src/types/CalendarDay/views/Field.js]: `htmlID` is `ks-input-${field.path}`, though. A different value.

File: packages/arch/packages/day-picker/src/TextDayPicker.js [hunk 2]
```diff
@@ -1,29 +1,35 @@
...
 
   return (
     <Input
       value={value}
       placeholder="Enter a date..."
       onBlur={() => {
-        let newDate = parseDate(value);
+        const newDate = parseDate(value);
         onChange(newDate);
         setValue(formatDate(newDate));
```
Comment (MadeByMike) [inline packages/arch/packages/day-picker/src/TextDayPicker.js]: We should validate the date format and if it is valid don't set the value.

File: packages/fields/src/types/CalendarDay/views/Field.js (hunk 1 above)
Comment (Vultraz) [reply packages/fields/src/types/CalendarDay/views/Field.js]: Also looks like the tests look for that value (`ks-daypicker-`).

Comment (MadeByMike) [reply packages/fields/src/types/CalendarDay/views/Field.js]: They need to be the same because we have `htmlFor={htmlID}` and this need to match the id on the input.

My suggestion is to change `const htmlID = `ks-input-${field.path}`;` to match

Comment (Vultraz) [reply packages/fields/src/types/CalendarDay/views/Field.js]: Ok, changed `htmlID`.
