### PR TITLE
Fix Admin UI crash when saving an item with a cards relationship field when another item is added to the relationship since the item was initially loaded

### LINKED ISSUE #7590: UI breaks when adding data to a field with ui.displayMode === "cards"
### Discussed in https://github.com/keystonejs/keystone/discussions/7472

<div type='discussions-op-text'>

<sup>Originally posted by **PhilBookst** April 19, 2022</sup>
Hey guys, I encountered an error with the Card component. I tried adding data to a field with `ui.displayMode === "cards"` using a resolveInputHook and got this error message after saving:
 
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'get')

Call Stack
eval
../../../../node_modules/@keystone-6/core/fields/types/relationship/views/dist/keystone-6-core-fields-types-relationship-views.esm.js (611:0)
Array.map
<anonymous>
eval
../../../../node_modules/@keystone-6/core/fields/types/relationship/views/dist/keystone-6-core-fields-types-relationship-views.esm.js (606:5)
Array.map
<anonymous>
Cards
../../../../node_modules/@keystone-6/core/fields/types/relationship/views/dist/keystone-6-core-fields-types-relationship-views.esm.js (573:3)
renderWithHooks
../../../../node_modules/react-dom/cjs/react-dom.development.js (14985:0)
updateFunctionComponent
../../../../node_modules/react-dom/cjs/react-dom.development.js (17356:0)
beginWork
../../../../node_modules/react-dom/cjs/react-dom.development.js (19063:0)
HTMLUnknownElement.callCallback
../../../../node_modules/react-dom/cjs/react-dom.development.js (3945:0)
Object.invokeGuardedCallbackDev
../../../../node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
../../../../node_modules/react-dom/cjs/react-dom.development.js (4056:0)
beginWork$1
../../../../node_modules/react-dom/cjs/react-dom.development.js (23964:0)
performUnitOfWork
../../../../node_modules/react-dom/cjs/react-dom.development.js (22776:0)
workLoopSync
../../../../node_modules/react-dom/cjs/react-dom.development.js (22707:0)
renderRootSync
../../../../node_modules/react-dom/cjs/react-dom.development.js (22670:0)
performSyncWorkOnRoot
../../../../node_modules/react-dom/cjs/react-dom.development.js (22293:0)
eval
../../../../node_modules/react-dom/cjs/react-dom.development.js (11327:0)
unstable_runWithPriority
../../../../node_modules/scheduler/cjs/scheduler.development.js (468:0)
runWithPriority$1
../../../../node_modules/react-dom/cjs/react-dom.development.js (11276:0)
flushSyncCallbackQueueImpl
../../../../node_modules/react-dom/cjs/react-dom.development.js (11322:0)
flushSyncCallbackQueue
../../../../node_modules/react-dom/cjs/react-dom.development.js (11309:0)
scheduleUpdateOnFiber
../../../../node_modules/react-dom/cjs/react-dom.development.js (21893:0)
dispatchAction
../../../../node_modules/react-dom/cjs/react-dom.development.js (16139:0)
MutationData.updateResult
../../../../node_modules/@apollo/client/react/data/MutationData.js (107:0)
MutationData.onMutationCompleted
../../../../node_modules/@apollo/client/react/data/MutationData.js (79:0)
eval
../../../../node_modules/@apollo/client/react/data/MutationData.js (18:0)
```

my list config for the field looks like this: 
```ts
    medicalQuestion: relationship({
      ref: "MedicalQuestionList",
      many: true,
      ui: {
        displayMode: "cards",
        inlineConnect: false,
        linkToItem: false,
        cardFields: ["question", "answer"],
        inlineCreate: { fields: ["question", "answer"] },
        inlineEdit: { fields: ["question", "answer"] },
      },
      hooks: {
        resolveInput: async ({ resolvedData, item, context, fieldKey }) => {
        // truncated logic
            const questionIds = questions.map(({ id }) => id)

            const questionLists = await context.query.MedicalQuestionList.createMany({
              data: questionIds.map(id => ({
                question: {
                  connect: { id }
                }
              })),
              query: "id"
            })

            resolvedData[fieldKey] = {
              set: undefined,
              disconnect: [],
              connect: questionLists?.map(({ id }) => ({ id })) ?? []
            }
            
          } catch (err) {
            console.error("err", err)
          }

          return resolvedData[fieldKey]
        }
      }
    }),
```

If `ui.displayMode === "select"` it works without a problem 

I attached a video so you can see the difference

https://user-images.githubusercontent.com/68562883/163886788-577c9745-b7ca-404f-bd10-ec9eb9fff422.mov
</div>

### PR DESCRIPTION
**Pull request by emmatown**
Closes #7590

### CODE REVIEW

File: tests/sandbox/configs/7590-add-item-to-relationship-in-hook-cards-ui.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+      name: text(),
+      numbers: relationship({
+        ref: 'Number.user',
+        many: true,
+        ui: {
+          displayMode: 'cards',
+          cardFields: ['value'],
+        },
+        hooks: {
+          // every time you save, add a random  number
```
Comment (mitchellhamilton) [inline tests/sandbox/configs/7590-add-item-to-relationship-in-hook-cards-ui.ts:17]:
```suggestion
          // every time you save, add a random number
```

File: packages/core/src/fields/types/relationship/views/cards/index.tsx [hunk 2]
```diff
@@ -154,6 +154,9 @@ export function Cards({
       >
         {[...value.currentIds].map((id, index) => {
           const itemGetter = items[id];
+          if (!itemGetter) {
+            return null;
+          }
```
Comment (dcousens) [inline packages/core/src/fields/types/relationship/views/cards/index.tsx:159]: Could we improve the type of `items` to lint for this?

**Review by dcousens — APPROVED** [review]

File: packages/core/src/fields/types/relationship/views/cards/index.tsx (hunk 2 above)
Comment (mitchellhamilton) [reply packages/core/src/fields/types/relationship/views/cards/index.tsx:159]: Not practically - could technically make the type `Record<string, Blah | undefined>` but that would be conceptually wrong and mean having to do a non-null assertion in places or we could use `noUncheckedIndexedAccess` but that would mean _a lot_ of errors and a lot of non-null assertions
