### PR TITLE
Check x-forwarded-host before host for support reverse proxy defaults

### LINKED ISSUE #4902: Keystone-next Admin UI refresh loop on nginx reverse proxy
# Bug report

When I start Keystone-next example projects, for example "examples-next/todo", all works well when I open the Admin UI in browser directly (using listening port, `http://example.com:3000/`).
But when I configure reverse proxy via nginx (`https://example.com/`) - I got the infinite loop of page refresh:
```
Something went wrong.
Unhandled Runtime Error
Error: An error occurred when loading Admin Metadata
Call Stack
useKeystone
webpack-internal:///../../../../packages-next/admin-ui/context/dist/admin-ui.esm.js (415:11)
```
And in output of keystone-next console - repeating error:
```
{"level":50,"time":1613990145346,"pid":23190,"hostname":"example.com","name":"graphql","message":"Access denied","locations":[{"line":3,"column":5}],"path":["keystone","adminMeta"],"uid":"cklgg26gj0000w6xxxug1ajz9","name":"GraphQLError","stack":"node_modules/@keystone-next/admin-ui/system/dist/admin-ui.cjs.dev.js:548:19\nrunMicrotasks (<anonymous>)\n"}
```

## To Reproduce

1. Start the  "examples-next/todo" app.
2. Open the Admin UI interface (http://localhost:3000/) directly in browser - all works well, you will see user register form.
3. Configure nginx host with https or even http, and reverse proxy to the app port:
```
location / {
  proxy_pass http://localhost:3000/;
  # Set additional headers on the upstream request
  proxy_set_header   X-Real-IP           $remote_addr;
  proxy_set_header   X-Forwarded-For     $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Proto   $scheme;
  proxy_set_header   X-Forwarded-Host    $host;
  proxy_set_header   X-Forwarded-Port    $server_port;
}
```
4. Try to open the proxied domain (https://example.com/) and got the infinite loop.
5. Same problem is with development mode (`yarn dev`).

Full error output:
```
Unhandled Runtime Error

Error: An error occurred when loading Admin Metadata
Call Stack
useKeystone
webpack-internal:///../../../../packages-next/admin-ui/context/dist/admin-ui.esm.js (415:11)
InitPage
webpack-internal:///../../../../packages-next/auth/pages/InitPage/dist/auth.esm.js (273:90)
renderWithHooks
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (14985:27)
mountIndeterminateComponent
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (17811:13)
beginWork
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (19049:16)
callCallback
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (3945:14)
invokeGuardedCallbackDev
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (3994:16)
invokeGuardedCallback
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (4056:31)
beginWork$1
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (23959:28)
performUnitOfWork
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (22771:12)
workLoopSync
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (22702:22)
renderRootSync
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (22665:7)
performSyncWorkOnRoot
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (22288:18)
flushSyncCallbackQueueImpl/<
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (11327:26)
unstable_runWithPriority
webpack-internal:///../../../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js (646:12)
runWithPriority$1
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (11276:10)
flushSyncCallbackQueueImpl
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (11322:26)
flushSyncCallbackQueue
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (11309:3)
scheduleUpdateOnFiber
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (21888:9)
dispatchAction
webpack-internal:///../../../../node_modules/react-dom/cjs/react-dom.development.js (16139:26)

### PR DESCRIPTION
**Pull request by MurzNN**
Default setup of reverse proxies is to pass real host into `x-forwarded-host` key, with leaving `host` untouched. 
For not require special changes of reverse proxy settings to Keystone-next, I propose to check the `x-forwarded-host` before `host`.
Resolves #4902.

### CODE REVIEW

File: packages-next/auth/src/index.ts [hunk 1]
```diff
@@ -337,10 +337,11 @@ export function createAuth<GeneratedListTypes extends BaseGeneratedListTypes>({
           // Allow access to the adminMeta data from the /init path to correctly render that page
           // even if the user isn't logged in (which should always be the case if they're seeing /init)
           const headers = context.req?.headers;
+          const host = headers ? headers['x-forwarded-host'] || headers.host : null;
```
Comment (timleslie) [inline packages-next/auth/src/index.ts:340]:
```suggestion
          const host = headers ? headers['x-forwarded-host'] || headers['host'] : null;
```

File: .changeset/fast-meals-ring.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@keystone-next/auth': minor
```
Comment (timleslie) [inline .changeset/fast-meals-ring.md:2]:
```suggestion
'@keystone-next/auth': patch
```

File: .changeset/fast-meals-ring.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
...
+---
+
+Check x-forwarded-host before host for support reverse proxy defaults
```
Comment (timleslie) [inline .changeset/fast-meals-ring.md:5]:
```suggestion
Fixed a bug which prevented accessing the '/init` path from behind a reverse proxy.
```

**Review by timleslie — CHANGES_REQUESTED** [review]
Looks like a good fix, just a few changes to clean up the PR 👍

**Review by timleslie — APPROVED** [review]
This all looks good now, thanks for the PR 🙏
