### PR TITLE
Fix bug in context.executeGraphQL

### LINKED ISSUE #3184: context.executeGraphQL fails in custom query
Testing as of `dafad5602bfa6796aa4dadb21d89c8d10d73cd32`.

I have this custom query sitting around I had been using to test something awhile back:
```js
      resolver: async (item, { name }, context, info) => {
        const {
          errors,
          data: { allUsers },
        } = await context.executeGraphQL({
          query: `query {
            allUsers(where: { name: "${name}"}) {
              id
            }
          }`,
        });

        return !!allUsers;
      },
```

When trying to execute it, this happens:
```
          "stacktrace": [
            "ReferenceError: Cannot access 'context' before initialization",
            "    at Object.context.executeGraphQL (C:\\Users\\exodi\\Documents\\keystone-5\\packages\\keystone\\lib\\Keystone\\index.js:246:43)",
            "    at resolver (C:\\Users\\exodi\\Documents\\keystone-5\\demo-projects\\todo\\index.js:554:27)",
            "    at resolve (C:\\Users\\exodi\\Documents\\keystone-5\\packages\\keystone\\lib\\providers\\custom.js:118:18)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
```

Initially, I thought it might be a problem with the scope of the `context` variable being passed to `keystone.executeGraphQL`, so i tried:

```js
    context.executeGraphQL = ({ context: cc = context, query, variables }) =>
      this.executeGraphQL({ cc, query, variables });
```

But that gives:
```
          "stacktrace": [
            "TypeError: Cannot read property 'schemaName' of undefined",
            "    at Keystone.createContext (C:\\Users\\exodi\\Documents\\keystone-5\\packages\\keystone\\lib\\Keystone\\index.js:231:19)",
            "    at Keystone.executeGraphQL (C:\\Users\\exodi\\Documents\\keystone-5\\packages\\keystone\\lib\\Keystone\\index.js:253:22)",
            "    at Object.context.executeGraphQL (C:\\Users\\exodi\\Documents\\keystone-5\\packages\\keystone\\lib\\Keystone\\index.js:247:12)",
            "    at resolver (C:\\Users\\exodi\\Documents\\keystone-5\\demo-projects\\todo\\index.js:552:27)",
            "    at resolve (C:\\Users\\exodi\\Documents\\keystone-5\\packages\\keystone\\lib\\providers\\custom.js:118:18)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
```

Removing the `context` argument from `context.executeGraphQL` entirely *does* fix the issue, but @gautamsi said that might not be the right thing to do.

Relevant convo:
image

### PR DESCRIPTION
**Pull request by timleslie**
Fixes #3184

### CODE REVIEW

File: packages/keystone/lib/Keystone/index.js [hunk 1]
```diff
@@ -237,13 +237,15 @@ module.exports = class Keystone {
       totalResults: 0,
       maxTotalResults: this.queryLimits.maxTotalResults,
     };
-    const orig = { schemaName, authentication, skipAccessControl };
+    // Locally bind the values we use as defaults into an object to make
```
Comment (MadeByMike) [inline packages/keystone/lib/Keystone/index.js:240]: /shrug
