### PR TITLE
Use safeRequire instead of manual try-catch requires

### LINKED ISSUE #3908: Replace inline try/catch with safeRequire
### Steps to reproduce the behavior
In current state, the following is copied throughout the codebase:

```javascript
try {
  return require('some unbundled lib');
catch (e) {
  if (e.code === 'MODULE_NOT_FOUND') {
    // do something
  }
  throw e;
}
```

we can replace this in these places with the new safeRequire function from #3907 for consistency.

### PR DESCRIPTION
**Pull request by thejameskyle**
Resolves #3908

### CODE REVIEW

File: lib/safeRequire.js [hunk 1]
```diff
@@ -3,7 +3,9 @@ module.exports = function safeRequire (library, feature) {
 		return require(library);
 	} catch (error) {
 		if (error.code === 'MODULE_NOT_FOUND') {
-			throw new Error('\nTo use ' + feature + ' install ' + library);
+			console.error('\nTo use ' + feature + ' install ' + library);
+			process.exit(1);
```
Comment (thejameskyle) [inline lib/safeRequire.js]: I switched to using `process.exit(1)` because most of these cases were already doing that and it seems to make more sense.

File: lib/safeRequire.js [hunk 2]
```diff
@@ -3,7 +3,9 @@ module.exports = function safeRequire (library, feature) {
...
+			return;
```
Comment (bassjacob) [inline lib/safeRequire.js]: why return after a `process.exit(1)` ?

Comment (thejameskyle) [inline lib/safeRequire.js]: Became a habit because of Flow

Comment (bassjacob) [inline lib/safeRequire.js]: ah, the always return even null. a null return after an IO call seems even weirder from a type system perspective :stuck_out_tongue:

**Comment by export-mike** [comment]
LGTM 👍  @Noviny @blargity @JedWatson
