### PR TITLE
fixes #6075

### LINKED ISSUE #6075: Website: heading level fragment identifiers don't work when emoji exist in the heading
On the Keystone website, subheadings in document pages generate a fragment identifier. For example:

https://keystonejs.com/docs/guides/document-fields#configuration

But when the `<Emoji>` component is included in a subheading ([example](https://github.com/keystonejs/keystone/blame/master/docs/pages/releases/2021-06-30.mdx#L19)) expected behaviour breaks.

---

## Within the body

The URL generated by clicking on the heading element ends up as:
https://keystonejs.com/releases/2021-06-30#

Instead of:
https://keystonejs.com/releases/2021-06-30#field-options-hotfix

### To Reproduce

1. Go to https://keystonejs.com/releases/2021-06-28
2. Click on the link icon that appears to the left of any of the `H3` level headings on hover.
3. Evaluate the fragment appended to the URL. It should have a `#` only.

---

## Within the right hand sidebar Table of Contents

When emoji component is present: links in the sidebar Table of Contents generate the correct fragment IDs but the page does not scroll down to the intended heading.

### To Reproduce

1. Go to https://keystonejs.com/releases/2021-06-28
2. Click on the right sidebar TOC links.
3. Evaluate the changed fragment ID in URL, but notice lack of redirection to subheading

### PR DESCRIPTION
**Pull request by dominikwilkowski**
TODO: needs to fix the TS types

### CODE REVIEW

File: docs/components/docs/Heading.tsx [hunk 1]
```diff
@@ -9,11 +9,14 @@ import { CopyToClipboard } from './CopyToClipboard';
  * !THIS IS OLD. PLEASE USE THE Type COMPONENT INSTEAD!
  */
 
-function getAnchor(text: string) {
+function getAnchor(text: string | array) {
```
Comment (timleslie) [inline docs/components/docs/Heading.tsx:12]:
```suggestion
function getAnchor(text: string | string[]) {
```

**Review by timleslie — APPROVED** [review]
👍
